<a href="https://colab.research.google.com/github/davidchois/Aplicadas-1/blob/main/Taller2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Taller 2:*
##*Nombres:*
### David Gonzalez Chois A00410841
### Leonardo Andres Muñoz  A00412196
### Luis Miguel Zambrano Sapuyes A00411441
### Jose Manuel Alvarez Ruano A00411201

## **Ejercicio 1:**



In [29]:
def es_primo(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

def filtrar_primos(lista):
    return [num for num in lista if es_primo(num)]

numeros = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19]
primos = filtrar_primos(numeros)
print("Numeros primos en la lista:", primos)

Números primos en la lista: [2, 3, 5, 7, 11, 13, 17, 19]


## **Ejercicio 2:**

In [30]:
def elementos_comunes(lista1, lista2):
    return list(set(lista1) & set(lista2))

lista_a = [1, 2, 3, 4, 5, 6, 7]
lista_b = [5, 6, 7, 8, 9, 10]
comunes = elementos_comunes(lista_a, lista_b)
print("Elementos comunes:", comunes)

Elementos comunes: [5, 6, 7]


## **Ejercicio 3:**

In [31]:
import numpy as np

def matriz_cuadrada(lista):
    n = len(lista)
    raiz = int(np.sqrt(n))

    if raiz * raiz != n:
        return "Error: La cantidad de elementos no permite formar una matriz cuadrada."

    matriz = np.array(lista).reshape(raiz, raiz)
    return matriz

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
resultado = matriz_cuadrada(lista)
print(resultado)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## **Ejercicio 4:**

In [ ]:
from statistics import mean, median, multimode
def calcular_estadisticas(lista):
    if not lista:
        return "La lista esta vacia."
    media = mean(lista)
    mediana = median(lista)
    moda = multimode(lista)
    return {
        "Media": media,
        "Mediana": mediana,
        "Moda": moda
    }
numeros = (1, 2, 7, 3, 4, 4, 5, 6)
resultado = calcular_estadisticas(numeros)
print(resultado)

{'Media': 4, 'Mediana': 4.0, 'Moda': [4]}


## **Ejercicio 5:**

In [ ]:
def calcular_total(precios, cantidades):
    if len(precios) != len(cantidades):
        return "Error: Las listas deben tener la misma cantidad de elementos."
    total = sum(precio * cantidad for precio, cantidad in zip(precios, cantidades))
    if total > 100:
        total *= 0.9
    return round(total, 2)
precios = (20, 15, 30, 10)
cantidades = (2, 1, 3, 4)
total_pagar = calcular_total(precios, cantidades)
print("Total a Pagar:", total_pagar)

Total a Pagar: 166.5


## **Ejercicio 6:**

In [ ]:
def actualizar_inventario(inventario, vendidos):
    return [producto for producto in inventario if producto not in vendidos]
inventario = ("manzanas", "bananas", "naranjas", "peras", "uvas")
vendidos = ("bananas", "peras")
inventario_actualizado = actualizar_inventario(inventario, vendidos)
print("Inventario actualizado:", inventario_actualizado)

Inventario actualizado: ['manzanas', 'naranjas', 'uvas']


## **Ejercicio 7:**

In [ ]:
def clasificar_temperaturas(temperaturas):
    dias_calidos = sum(1 for t in temperaturas if t > 30)
    dias_temperados = sum(1 for t in temperaturas if 20 <= t <= 30)
    dias_frios = sum(1 for t in temperaturas if t < 20)
    return {
        "Dias calurosos (>30°C)": dias_calidos,
        "Dias templados (20°C-30°C)": dias_temperados,
        "Dias fríos (<20°C)": dias_frios
    }
temperaturas = (18, 22, 25, 30, 32, 28, 19, 15, 35, 29, 31, 21)
resultado = clasificar_temperaturas(temperaturas)
print(resultado)

{'Días calurosos (>30°C)': 3, 'Días templados (20°C-30°C)': 6, 'Días fríos (<20°C)': 3}


## **Ejercicio 8:**

In [ ]:
def calcular_calorias(alimentos, calorias):
    if len(alimentos) != len(calorias):
        return "Error: La lista de alimentos y la de calorías deben tener la misma longitud."
    total_calorias = sum(calorias)

    if total_calorias > 2000:
        mensaje = (f"Total de calorías consumidas: {total_calorias}.\n"
                  "Has superado las 2000 calorias diarias recomendadas.")
    else:
        mensaje = (f"Total de calorías consumidas: {total_calorias}."
                   "Estás dentro del rango recomendado de calorias diarias.")

    return mensaje


alimentos = ["Manzana", "Sandwich", "Ensalada", "Galletas"]
calorias = [95, 350, 150, 1800]

print("Calculadora de calorias consumidas:")
print(calcular_calorias(alimentos, calorias))

Calculadora de calorias consumidas:
Total de calorías consumidas: 2395.
Has superado las 2000 calorías diarias recomendadas.


## **Ejercicio 9:**

In [ ]:
def promedio_ventas(ventas):
    if len(ventas) != 12:
        return "Error: Debe haber 12 valores de ventas mensuales."
    else:
      prom = sum(ventas) / 12
      meses_encima = len([v for v in ventas if v > prom])
      return prom, meses_encima


ventas_mensuales = [1200, 1500, 1300, 1400, 1600, 1700, 2000, 1900, 1800, 1750, 1650, 1550]
promedio, meses_superiores = promedio_ventas(ventas_mensuales)

print("VENTAS:")
print("Promedio de ventas mensuales:", promedio)
print("Meses por encima del promedio:", meses_superiores)

VENTAS:
Promedio de ventas mensuales: 1612.5
Meses por encima del promedio: 6


## **Ejercicio 10:**

In [ ]:
def aplicar_descuento(total):
    if 50 <= total <= 100:
        descuento = 0.05
    elif 100 < total < 200:
        descuento = 0.10
    elif total >= 200:
        descuento = 0.15
    else:
        descuento = 0

    total_con_descuento = total - (total * descuento)
    return total_con_descuento

compra1 = 75
compra2 = 150
compra3 = 250
print("Sistema de descuentos de la tienda:")
print("Total final de compra No.1: $", aplicar_descuento(compra1))
print("Total final de compra No.2: $", aplicar_descuento(compra2))
print("Total final de compra No.3: $", aplicar_descuento(compra3))

Sistema de descuentos de la tienda:
Total final de compra No.1: $ 71.25
Total final de compra No.2: $ 135.0
Total final de compra No.3: $ 212.5


## **Ejercicio 11:**

In [ ]:
def pacientes_prioritarios(names, ages):
    prioritarios = []
    for i in range(len(names)):
        if ages[i] > 60:
            prioritarios.append(names[i])
    return prioritarios

names = ["Jose", "Leonardo", "Luis", "David"]
ages = [14, 75, 82, 34]

prioritarios = pacientes_prioritarios(names, ages)

print("Estos pacientes requieren atencion prioritaria:", prioritarios)



Estos pascientes requieren atencion priritaria: ['Leonardo', 'Luis']


## **Ejercicio 12:**

In [ ]:
def calcular_gastos(mes, categorias, gastos):
    total_gastos = 0
    gasto_maximo = gastos[0]
    categoria_maxima = categorias[0]

    for i in range(len(gastos)):
        total_gastos += gastos[i]
        if gastos[i] > gasto_maximo:
            gasto_maximo = gastos[i]
            categoria_maxima = categorias[i]

    print("El total de gastos de", mes, "fue de:", total_gastos)
    print("El gasto mas alto de este mes fue de:", gasto_maximo, "en la categoria de", categoria_maxima)

mes = input("Ingrese el mes: ")
categorias = ["Seguro", "Comida", "Transporte", "Entretenimiento", "Servicios", "Universidad"]
gastos = [250, 300, 100, 150, 200, 600, 500]

calcular_gastos(mes, categorias, gastos)


Ingrese el mes: Enero
El total de gastos de Enero fue de: 2100
El gasto mas alto de este mes fue de: 600 en la categoria de Universidad


## **Ejercicio 13:**

In [ ]:
def lista_inasistentes(registrados, asistentes):
    no_asistentes = []
    for persona in registrados:
        if persona not in asistentes:
            no_asistentes.append(persona)
    return no_asistentes

registrados = ["Luis", "Jose", "Leonardo", "David"]
asistentes = ["Leonardo", "David"]

no_asistentes = lista_inasistentes(registrados, asistentes)

print("Las personas que no asistieron fueron:", no_asistentes)



Las personas que no asistieron fueron: ['Luis', 'Jose']


## **Ejercicio 14:**

In [ ]:
nombre = input("Ingrese su nombre: ")
def ejercicio_promedio(ejercicio):
    total_minutos = 0

    for minutos in ejercicio:
        total_minutos += minutos

    promedio = total_minutos / len(ejercicio)

    if promedio > 60:
        mensaje = "Excelente, estas en forma"
    elif promedio >= 30:
        mensaje = "Buen trabajo, pero puedes mejorar"
    else:
        mensaje = "Debes hacer mas ejercicio"

    print(nombre,"Su promedio diario de ejercicio fue de :", promedio)
    print(mensaje)

ejercicio = [60, 50, 90, 70, 80, 20, 60]

ejercicio_promedio(ejercicio)



Ingrese su nombre: David
David  Su promedio diario de ejercicio fue de : 61.42857142857143
Excelente, estas en forma
